name: kg-sv-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - werkzeug=3.0.1
  - flask=3.0.2
  - networkx=3.2.1
  # - matplotlib=3.8.3
  # - scikit-learn=1.3.2
  - pip=23.2.1
  - pytorch=1.13.1
  - flask-cors=4.0.0
  - bleach=6.1.0
  - gunicorn=21.2.0
  - python-dotenv=1.0.0 
  # - cudatoolkit=11.6 
  - pip:
    # - huggingface_hub==0.12.0
    # - tokenizers==0.13.2
    # - transformers==4.26.0
    # - sentence-transformers==2.2.2
    - tqdm>=4.27
    - requests>=2.25.1