name: kg-sv-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.23.5
  - werkzeug=2.0.3
  - flask=2.0.1
  - networkx=2.8.4
  - matplotlib=3.5.3
  - scikit-learn=1.0.2
  - pip=22.2.2
  - pytorch=1.13.1
  - flask-cors
  - cudatoolkit=11.6  # Remove if not using GPU
  - bleach
  - pip:
    - huggingface_hub==0.12.0
    - tokenizers==0.13.2
    - transformers==4.26.0
    - sentence-transformers==2.2.2
    - tqdm>=4.27
    - requests>=2.25.1 