name: kg-sv-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - werkzeug>=3.1.0
  - flask=3.1.0
  - networkx=3.2.1
  - matplotlib=3.8.3
  - scikit-learn=1.3.2
  - pip=23.2.1
  - pytorch=2.7.0
  - flask-cors=5.0.1
  - bleach=6.2.0
  - gunicorn=23.0.0
  - python-dotenv=1.0.0 
  # - cudatoolkit=11.6 
  - pip:
    - huggingface_hub==0.31.1
    - tokenizers==0.21.1
    - transformers==4.51.3
    - sentence-transformers==4.1.0
    - tqdm>=4.27
    - requests>=2.25.1